import React, { Component } from "react";
import axios from "axios";
import ListImages from "./components/ListImages";
import ListVideos from "./components/ListVideos";
import ListOtherVids from "./components/ListOtherVids";
import HostedVideos from "./components/HostedVideos";


class App extends Component {
  state = {
    data: [],
    subreddit: "",
    after: "",
    before: "",
    url: "https://www.reddit.com/r/",
    jsonStr: ".json?limit=30",
    afterStr: "&after=",
    beforeStr: "&before="
  };

  handleChange = async e => {
    await this.setState({
      subreddit: e.target.value, subreddit: e.target.getAttribute('name')
    });

    const link = this.state.subreddit;
    const url = "https://www.reddit.com/r/";

    // axios.get(url + link + this.state.jsonStr).then(response => {
    //   this.setState({
    //     data: response.data.data.children,
    //     after: response.data.data.after
    //   });
    // });

    const myResponse = await axios.get(url+link+this.state.jsonStr);
    this.setState({
      data: myResponse.data.data.children,
      after: myResponse.data.data.after
    })

  };
  handleSubmit = e => {
    e.preventDefault();
    const link = this.state.subreddit;
    const url = "https://www.reddit.com/r/";
    console.log(url + link + ".json?limit=10");
  };

  stateFunction = (e) =>{
    this.setState({subreddit: e.target.getAttribute('name')})
  }

  handleNext = () => {
    axios
      .get(
        this.state.url +
          this.state.subreddit +
          this.state.jsonStr +
          this.state.afterStr +
          this.state.after
      )
      .then(response => {
        this.setState({
          data: response.data.data.children,
          after: response.data.data.after
        });
      });
  };

  handleNsfwClick = (e) =>{
    this.setState({subreddit: e.target.getAttribute('name')})
  }
  componentWillMount() {}
  componentDidMount() {
    // axios
    //  .get(
    //    "https://www.reddit.com/r/foodporn.json?&limit=10"
    //  )
    // .then(response => {
    //   console.log(response.data.data.after)
    //    this.setState({data: response.data.data.children})
    //  });
  }

  render() {
    const images = this.state.data.filter(vals => {
      return vals.data.post_hint === "image";
    });
    const links = this.state.data.filter(vals => {
      return vals.data.post_hint === "link";
    });
    const hosted = this.state.data.filter(vals => {
      return vals.data.post_hint === "hosted:video";
    });

const nsfwLinks = ["1000CCPLUS","1819CLUB","18PLUSGIFS","18_19","2000SGIRLS","2BOOTY","3DPORNCRAFT","40PLUSGONEWILD","5050PICS","60FPSPORN","8MUSES","AA_CUPS","ABDL","ABELLADANGER","ABUSEDSLUTS","ABUSEPORN2","ACCIDENTALNUDE","ADORABLEPORN","ADORABLE_GIRLS","ADRIANACHECHIK","ADULTNEEDS","ADULT_SOCIAL_NETWORK","AFFAIRS","AFRODISIAC","AFTERTHESHOT","AGEDBEAUTY","AHEGAO","AHEGAOGIRLS","AHEGAO_IRL","AJELQFORYOU","ALASJUICY","ALBUMBABES","ALEXAPEARL","ALEXASMORGAN","ALEXISTEXAS","ALLABOUTBOOBS","ALLADULTNSFW","ALLISONPARKERFANS","ALLTHEWAYTHROUGH","ALTEREDBUTTHOLES","ALTGONEWILD","ALVAJAYXXX","AMANDACERNY","AMATEUR","AMATEURBLOWJOB","AMATEURCUMSLUTS","AMATEURDEEPTHROAT","AMATEURGIRLSBIGCOCKS","AMATEURGROUPS","AMATEURINCEST","AMATEURNUDESWITHFACE","AMATEURPORN","AMATEURPORNVIDS","AMATEURSLUTWIVES","AMATEURTEEN_PORN","AMATEUR_MILFS","AMATEUR_THREESOMES","AMAZINGCURVES","AMAZINGTITS","AMBERHAYES","ANACHERIEXCLUSIVE","ANAL","ANALGONEWILD","ANALGW","ANALINSERTIONS","ANALORGASMS","ANAL_GIFS","ANAL_WITCH","ANDROIDNSFWGAMING","ANGELAWHITE","ANIMEBOOTY","ANIMEFEET","ANIMEMILFS","ANNOYEDTOBENUDE","ANRIOKITA","ARABPORN","AREOLASGW","ARIANAGRANDELEWD","ASAAKIRA","ASHE_MAREE","ASHLEYALBAN","ASIANAMERICANPORN","ASIANCUMSLUTS","ASIANCUTIES","ASIANGIRLSWHITECOCKS","ASIANHOTTIES","ASIANNSFW","ASIANPORN","ASIANSGONEWILD","ASIANTRAPS","ASIAN_GIFS","ASKREDDITAFTERDARK","ASS","ASSHOLE","ASSHOLEBEHINDTHONG","ASSHOLEGONEWILD","ASSINTHONG","ASSLICK","ASSTASTIC","ATHLETICBABES","ATHLETICGIRLS","AUTUMNFALLS","AVAADDAMS","AVATARPORN","AVERAGEPENIS","AZEROTHPORN","AZURLEWD","BABECOCK","BABESNSFW","BADDRAGON","BAILEYJAY","BALLBUSTING","BALLS","BALLSDEEPANDCUMMING","BANGMYBULLY","BARELYCLOTHED","BARELYLEGAL","BARELYLEGALTEENS","BBCPARADISE","BBCSISSIES","BBCSLUTS","BBW","BBWGW","BBWVIDEOS","BBW_CHUBBY","BDSM","BDSMCOMMUNITY","BDSMGW","BDSMPERSONALS","BEACHGIRLS","BECKYCROCKER","BEFORE_AFTER_CUMSLUTS","BELLEDELPHINELEWDS","BELLEDELPHINEPATREON","BESTHQPORNGIFS","BESTOFLIVELEAK","BESTPORNINGALAXY","BESTSNAPCHATNUDES","BESTTITS","BETHLILY","BICUCKOLD","BIGAREOLAS","BIGASSES","BIGBLACKBOOTYGIFS","BIGBOOBSGONEWILD","BIGBOOBSGW","BIGBROTHERNSFW","BIGCLIT","BIGDICKGIRL","BIGDICKJOY","BIGDICKLOVERS","BIGGERTHANHERHEAD","BIGGERTHANYOUTHOUGHT","BIGONEWILD","BIGTIDDYGOTHGF","BIGTITSBUTCLOTHED","BIKINIBODIES","BIKINIS","BILLIEEILISHGW","BILLIEEILISHTHICC","BIMBOFETISH","BIMBOFICATION","BISEXUALFANTASY","BISEXY","BITEDSIZESEXY","BLACKCHICKSWHITEDICKS","BLACKED","BLACKGIRLBLOWJOBS","BLACKWORLDORDER","BLONDE","BLONDEGIRLSFUCKING","BLOWJOB","BLOWJOBGIFS","BLOWJOBGIRLS","BLOWJOBS","BLOWJOBSANDWICH","BMOVIEBABES","BODYPERFECTION","BODYSHOTS","BODYSUIT","BOIS","BOKUNOEROACADEMIA","BOLTEDONBOOTY","BOLTEDONTITS","BONDAGE","BONDAGE_PORN","BONERALERT","BONERFUEL","BONERMATERIAL","BONERSINPUBLIC","BONGBEAUTY","BOOBBOUNCE","BOOBIES","BOOBS","BOOBSANDTITIES","BOOMERHENTAI","BOOTY","BOOTYPETITE","BOOTYSHORTS","BOOTY_QUEENS","BOREDNIGNORED","BOTTOMLESS_VIXENS","BOUNCINGTITS","BOWSETTE","BOYPUSSY","BRACEFACE","BRALESS","BRANDILOVE","BRAZZERS","BREAKINGTHESEAL","BREAK_YO_DICK_THICK","BREASTENVY","BREASTEXPANSION","BREASTSUCKING","BREEDING","BREEDINGMATERIAL","BREELOUISEXOXO","BROSLIKEUS","BROWNHOTTIES","BUBBLEBUTTS","BUKKAKE","BULGES","BUNDLEOFBRITTANY","BURSTINGOUT","BUSTY","BUSTYASIANS","BUSTYPETITE","BUSTY_GIRLS","BUTTPLUG","BUTTSANDBAREFEET","BUTTSHARPIES","CAMELTOE","CAMELTOEONOFF","CAMSLUTS","CAMSODA","CAMWHORES","CAM_GIFS","CANTHOLD","CARTOON_PORN","CASSIE0PIA","CASUALJIGGLES","CASUALNUDITY","CAUGHTANDCONTINUED","CAUGHTFUCKING","CEDEHSGIFS","CEDEHSHENTAI","CELEBECONOMY","CELEBJOBUDS","CELEBNSFW","CELEBNUDES","CELEBRITYBUTTS","CELEBRITYCANDIDS","CELEBRITYNIPPLES","CELEBRITYPENIS","CELEBRITYPUSSY","CELEBSEXSCENES","CELEBSGW","CELEBSNAKED","CENTAURGIRLS","CFNM","CHANGINGROOMS","CHASTITY","CHASTITYCOUPLES","CHAVGIRLS","CHEATINGCAPTIONS","CHEATINGSLUTS","CHEATINGWIVES","CHEERLEADERSGONEWILD","CHICAGOR4R","CHICKFLIXXX","CHRISTIANGIRLS","CHRISTYMACK","CHUBBY","CHURCHOFTHEBBC","CLARABABYLEGS","CLEAVAGE","CLOPCLOP","CLOTHEDTITFUCK","CLOTHINGKINK","CNC_CONNECT","COCK","COLLARED","COLLEGEAMATEURS","COLLEGEINITIATION","COLLEGENSFW","COLLEGESLUTS","COLTISH","COMICS18_STORY","CONFUSEDBONERS","CONSENTACLES","CORYCHASE","COSPLAYBUTTS","COSPLAYLEWD","COSPLAYNSFW","COSPLAYONOFF","COUGARS","COUPLESGONEWILD","CREAMING","CREAMPIE","CREAMPIEGANGBANGS","CREAMPIEGIFS","CREAMPIES","CREEPYPASTAPORN","CRIMESCENE","CUCK","CUCKOLD","CUCKOLDCAPTIONS","CUCKOLDCOMMUNITY","CUCKOLDSTORIES","CUCKQUEAN","CUM","CUMAGAIN","CUMCANNONADDICTS","CUMCOVEREDFUCKING","CUMFETISH","CUMFLATION","CUMFROMANAL","CUMHATERS","CUMHENTAI","CUMINSIDEME","CUMMEDPANTIES","CUMONCLOTHES","CUMONTITS","CUMSHOTS","CUMSHOTSELFIES","CUMSLUTS","CUMTRIBUTES","CUNNILINGUS","CURVY","CUTEASFUCKBUTCLOTHED","CUTELITTLEBUTTS","CUTEMODESLUTMODE","DADDY","DADSANDBOYS","DADSGONEWILD","DADWOULDBEPROUD","DAISYTAYLOR","DAMNGOODINTERRACIAL","DANIDANIELS","DARKANGELS","DARKJOKES","DARK_HUMOR","DARSHELLECOSPLAY","DATGAP","DAUGHTERTRAINING","DBDGONEWILD","DBZ34","DDLCRULE34","DDLG","DDLGLEWDS","DDLGPERSONALS","DDLG_PORN","DEADEYES","DEEPTHROAT","DEGRADINGHOLES","DELICIOUSTRAPS","DEMIROSEMAWBY","DESIBONERS","DESIDESIRE","DILDO","DILDO_GIFS","DILLION_HARPER","DIRTYCONFESSION","DIRTYGAMING","DIRTYKIKPALS","DIRTYPENPALS","DIRTYR4R","DIRTYSEXYKIKPALS","DIRTYSMALL","DIRTYSNAPCHAT","DISNEYPORN","DISTENSION","DOGGY","DOGGYSTYLE_NSFW","DOMINATED","DOUBLEPENETRATION","DOUJINSHI","DOWNBLOUSE","DRAWMENSFW","DRUNKDRUNKENPORN","DRUNKGIRLS","DYKESGONEWILD","EBONY","EBONYAMATEURS","EBONYCUTIES","EBONYGIRLS","ECCHI","EDGING","EDIBLEBUTTHOLES","ELLEBROOKEUK","ELSAJEAN","EMILYBLOOM","EMILYLYNNE","EMILYWILLIS","EMMAGLOVER","EMOGIRLS","ENF","ENGORGEDVEINYBREASTS","ENVEE420","ERASERNIPPLES","ERINASHFORD","EROTICA","EROTICHYPNOSIS","EROTICLITERATURE","ERSTIES","ETHOTHUB","EVAELFIE","EVALOVIA","EVIEERIKSONPICS","EXHIBITIONISTSEX","EXPOSEDINPUBLIC","EXTRAMILE","EXXXCHANGE","EXXXTRAS","EYEBLECH","EYEROLLORGASM","F4M","FACEDOWNASSUP","FACEFUCK","FACESITTING","FACIAL","FACIALFUN","FAERYFAWN","FAIRYTAIL_HENTAI","FANTASTICBREASTS","FAPPEDTOTHAT","FAUXBAIT","FAY_SUICIDE","FEELTHEMUP","FEET","FEMALEORGASMDENIAL","FEMALEPOV","FEMBOYS","FEMDOM","FEMDOMGONEWILD","FEMDOM_GIFS","FEMYIFF","FESTIVALSLUTS","FETISH","FETISHLIFE","FILTHYASIANS","FILTHYGIRLS","FILTHYLATINAS","FILTHYTEENS","FINALLYDOESPORN","FINGERING","FIRE_EMBLEM_R34","FIRTSBORNUNICORN","FISHNETS","FISTING","FITGIRLS","FITGIRLSFUCKING","FITNAKEDGIRLS","FLASHINGANDFLAUNTING","FLASHINGGIRLS","FLESHLIGHT","FLORIDAR4R","FLUBTRASH","FMN","FOOTFETISH","FOOTJOBS","FORCEDBREEDING","FORCEDCREAMPIE","FORCEDORGASMS","FORESKIN","FORTYFIVEFIFTYFIVE","FREEUSE","FREEUSEFAMILY","FREEUSEHENTAI","FRIENDSGONEWILD","FROGBUTT","FTMPORN","FUCKDOLL","FUCKGAMING","FUCKINGPERFECT","FUCKINGTWEAKERS","FUCKMEAT","FUNPIECE","FUNSIZED","FUNWITHFRIENDS","FURRYKIKPALS","FURRYPORN","FURRYPORNSUBREDDIT","FUTADOMWORLD","FUTANARI","FUTANARIPEGGING","FUTANARI_COMICS","GABBIECARTER","GABBIE_CARTER","GAG_SPIT","GAMEDAYGONEWILD","GAMEOVERGIRLS","GANGBANG","GAPE","GAYBEARS","GAYBROSGONEWILD","GAYCRUISING","GAYCUMSLUTS","GAYGIFS","GAYINCEST","GAYKIKPALS","GAYMERSGONEWILD","GAYNSFW","GAYPORN","GAYPORNHUNTERS","GAYPORNWITHPLOT","GAYSEXCONFESSIONS","GAYSNAPCHAT","GAYSTORIESGONEWILD","GAYSTRUGGLEFUCK","GBR4R","GENTLEFEMDOM","GERMANCELEBRITIESFAP","GERMANSGONEWILD","GETTINGHERSELFOFF","GFTJCREAMPIE","GFUR","GHOSTNIPPLES","GIANNAMICHAELS","GIFSAUCES","GIFSGONEWILD","GIFSOFREMOVAL","GILF","GINGER","GIRLFRIENDPORN","GIRLSCONTROLLED","GIRLSDOINGSTUFFNAKED","GIRLSFARTING","GIRLSFINISHINGTHEJOB","GIRLSHUMPINGTHINGS","GIRLSINFLAREPANTS","GIRLSINYOGAPANTS","GIRLSKISSING","GIRLSMASTURBATING","GIRLSONTOP","GIRLSPOOPING","GIRLSSHOWERING","GIRLSWHORIDE","GIRLSWITHGIRLS","GIRLSWITHGLASSES","GIRLSWITHNEONHAIR","GLORYHO","GLORYHOLELOCATIONS","GLORYHOLES","GODASSHOLE","GODPUSSY","GOLEMSEXY","GONEEROTIC","GONEMILD","GONEWILD","GONEWILD18","GONEWILD30PLUS","GONEWILDAUDIBLE","GONEWILDAUDIO","GONEWILDCD","GONEWILDCHUBBY","GONEWILDCOLOR","GONEWILDCOUPLES","GONEWILDCURVY","GONEWILDGBUK","GONEWILDHAIRY","GONEWILDPLUS","GONEWILDSCRUBS","GONEWILDSMILES","GONEWILDSTORIES","GONEWILDTRANS","GONEWILDTUBE","GOODGIRLSSWALLOW","GOTHSLUTS","GROOL","GROOLTASTING","GROUPOFNUDEGIRLS","GROUPSEX","GSSPOT","GURO","GUYSFROMBEHIND","GWAUSTRALIA","GWBLACKGIRLS","GWCOUPLES","GWCUMSLUTS","GWNERDY","GWPUBLIC","HAIRY","HAIRYPUSSY","HALEIGH_COX","HANDHOLDING","HANDJOB","HANDJOBS","HANGERS","HARDBODIES","HARDCORENSFW","HARDPORNGIFS","HAZBINBROTHEL","HEALSLUTS","HELPLESSHENTAI","HENTAI","HENTAI4EVERYONE","HENTAIBEAST","HENTAIBONDAGE","HENTAIBREEDING","HENTAICAPTIONS","HENTAIFEMDOM","HENTAIMEMES","HENTAISOURCE","HENTAI_GIF","HENTAI_IRL","HETEROFLEXIBLE","HIGHHEELSNSFW","HIGHMILEAGEHOLES","HIGHRESNSFW","HIJABIXXX","HIPCLEAVAGE","HITOMI_TANAKA","HOLDTHEMOAN","HOLEWRECKERS","HOMEGROWNTITS","HOMEMADEGAYPORN","HOMEMADEGIFS","HOMEMADENSFW","HOMEMADEPORN","HOMEMADEXXX","HOMESEX","HOOKUP","HOPELESSSOFRANTIC","HORNY","HOTCHICKSWITHTATTOOS","HOTCLUB","HOTFALLINGDEVILZ","HOTMOMS","HOTPAST","HOTSTUFFNSFW","HOTWIFE","HOTWIFECAPTION","HOTWIFELIFESTYLE","HOTWIFEREQUESTS","HOTWIFETEXTS","HOTWIFEVIDEOS","HOWDEEPISYOURL0VE","HUGEBOOBS","HUGEBOOBSHARDCORE","HUGEDICKTINYCHICK","HUGEDILDOS","HUGEFUTANARI","HUGEHANGERS","HUMONGOUSAURUSTITS","HUNGRYBUTTS","HYPNOHENTAI","IFYOUHADTOPICKONE","ILOVESLUTS","IMGOINGTOHELLFORTHIS","IMPREGPERSONALS","IMPRESSSEDBYCUM","INCESTCOMICS","INCESTGIFS","INCESTPORN","INCESTSNAPS","INCESTSTORIES","INCEST_GIFS","INDIANBABES","INDIANGIRLS","INDIANPORN","INDIANSAFTERDARK","INDIANSGONEWILD","INNIE","INNIEPENETRATION","INSERTIONS","INSEX","INSTAGRAMHOTTIES","INSTAGRAMSLUTS","INSTANT_LOSS","INSTASNAPSANDMORE","IRCUCKOLD","ITSAMATEURHOUR","IWANTTOBEHER","IWANTTOBEHERHENTAI","IWANTTOFUCKHER","IWANTTOSUCKCOCK","JACKING","JANICEGRIFFITH","JAPANESEPORN2","JAPANESEUNCENSORED","JAPANUNCENSORED","JAVDOWNLOADCENTER","JAVDREAMS","JEMWOLFIE","JEMWOLFIEFANZ","JEMWOLFIE_","JEM_WOLFIE","JERKOFFTOCELEBS","JERKOFFTOMYMOM","JESSICANIGRI","JESSICASUNOK","JIA_LISSA","JIGGLEFUCK","JILLING","JIZZEDTOTHIS","JKFILMS_NSFW","JOBUDS","JOBUDS2","JOBUDSMEETUP","JODELNSFW","JOI","JOIP","JOJO34","JUICYASIANS","JULIAROSE","JUST18","JUSTFRIENDSHAVINGFUN","JUSTHOTWOMEN","KARLEEGREY","KATEEOWEN","KAYLENWARD","KAYLENWARDNUDE","KAYW","KEBABS0VERABS","KENDRALUST","KENDRA_SUNDERLAND","KEYHOLDERCAPTIONS","KIMMYGRANGER","KIRSTYAUSTINOF","KNOCKMEUP","KPOPFAP","KYLIEJENNER","LABIAGW","LACTATION","LADYBONERSGW","LADY_IN_THE_STREETS","LANARHOADES","LATINAS","LATINASGW","LAURAMUELLER","LAURENPISCIOTTA","LAURENSUMMER","LEAHGOTTI","LEGALTEENS","LEGALTEENSXXX","LEGGINGSGONEWILD","LEGS","LELE_PONS","LENAPAUL","LENA_THE_PLUG","LESBIANORAL","LESBIANS","LESBIAN_GIFS","LESDOM","LEWDGAMES","LEXIBELLE","LILIANAHEARTSSS_","LINDSEYPELAS","LINGERIE","LINGERIEGW","LIPSTHATGRIP","LISAANN","LITTLECAPRICE","LITTLESPACE","LIYASILVER","LOVEISLAND_NSFW","LUCIEWILDEISRETARDED","MADISON_IVY","MAITLANDWARD2","MALESMASTURBATING","MALMALLOY","MANGONEWILD","MANYVIDS","MARIAFERNANDA","MASALADESI","MASSAGEPORN","MASSIVECOCK","MASSIVETITSNASS","MASTEROFANAL","MASTURBATION","MASTURBATIONGONEWILD","MATINGPRESS","MATUREMILF","MEDICALGORE","MEGANRAIN","MEGASFORTHECULTURE","MENSHIGHJINX","METH","MEXICANA","MIAKHALIFA","MIAMALKOVA","MIAMELANO","MICROPENIS","MIDDLEEASTERNHOTTIES","MILF","MILFCUMSLUTS","MILFIE","MILFS","MILITARYGONEWILD","MILKINGTABLE","MISOGYNYFETISH","MISSALICE_18","MMGIRLS","MOLLYESKAMONLYFANS","MOMMYBULLY","MOMMY_TITS","MOMOKUN_MARIAHMALLAD","MOMSGONEWILD","MOMSON","MOMSONINCEST","MONSTERDICKS","MONSTERFACIALS","MONSTERGIRL","MONSTER_COCKS","MOONING","MORBIDREALITY","MORGANHULTGREN","MOUNDOFVENUS","MULTITASKERS","MYCLEAVAGE","MYHEROACADEMIAHENTAI","NAKED","NAKEDADVENTURES","NAKEDGIRLSDANCING","NAKEDONSTAGE","NAKEDPHILANTHROPIST","NARUTO_HENTAI","NATALEE","NATURALTITTIES","NAUGHTYFROMNEGLECT","NAUGHTYWIVES","NEKOIRL","NETORARE","NEXTDOORASIANS","NHENTAI","NICOLEANISTON","NIECEWAIDHOFER","NIGHTOUTGIRLS","NINTENDOWAIFUS","NIPPLES","NIPSLIPS","NNLEGALTEENS","NORMALNUDES","NOSTALGIAFAPPING","NSFW","NSFW2","NSFW411","NSFWASMR","NSFWBARISTA","NSFWCELEBS","NSFWCOSPLAY","NSFWCOSTUMES","NSFWCYOA","NSFWDISCORDS","NSFWFANTASYTEXTS","NSFWFASHION","NSFWFUNNY","NSFWGAMING","NSFWGIF","NSFWGIFSWITHPLOTS","NSFWHARDCORE","NSFWIAMA","NSFWMEMES","NSFWOUTFITS","NSFWVERIFIEDAMATEURS","NSFW_AMATEURS","NSFW_CHINA","NSFW_GIF","NSFW_GIFS","NSFW_HTML5","NSFW_JAPAN","NSFW_KOREA","NSFW_PLOWCAM","NSFW_SNAPCHAT","NSFW_SOCIAL","NSFW_TRIBUTES","NSFW_VIDEOS","NSFW_WTF","NUDEBEACH","NUDECELEBSONLY","NUDEFROG","NUDES","NUDESFEED","NUDE_SELFIE","NUDE_SNAPCHAT","NYR4R","OBSF","OCULUSNSFW","OHGEELIZZYP2","OHLYMPICS","OILPORN","OLDSCHOOLCOOLNSFW","OMEGLESEX","OMGBECKYLOOKATHISCOCK","OMGDYHAB","ONHERKNEES","ONLYAMATEURPORN","ONLYFANS101","ONLYFANSFREE","ONLYFANS_PROMO","ONLYHOES","ONLYIFSHESPACKIN","ONLYLESBIANS","ONMWW","ONOFF","ONOFFCELEBS","ONSTAGEGW","OOPSICAME","ORALCREAMPIE","ORGASMCONTROL","ORGASMICCONTRACTIONS","ORGASMS","ORGY","OUTERCOURSE","OVERHEARDSEX","OVERWATCH_PORN","OVIPOSITION","O_FACES","PAAG","PAGE3GLAMOUR","PAINAL","PALEGIRLS","PANTIES","PANTIESTOTHESIDE","PANTSU","PANTYHOSE","PANTYPEEL","PARODYPORNVIDEOS","PASSIONX","PAWG","PAWGSLUTS","PAWGTASTIC","PEE","PEEGONEWILD","PEGGING","PEGGING_UNKINKED","PELFIE","PENIS","PERFECTFAP","PERKYCHUBBY","PETAJENSEN","PETITE","PETITEGONEWILD","PETITENSFW","PHATBOOTYCUTIES","PHGONEWILD","PHONEJOBS","PICKONE","PIERCEDNIPPLES","PIERCEDNSFW","PILLOWHUMPING","PILLOWTALKAUDIO","PIPERPERRI","PIZZADARE","PLASTT","PLAYBOY","POKEPORN","POKIES","POKIMANENSFW","POLITICSNSFW","POONAMPANDEYFANATICS","PORN","PORNDIO","PORNGIFS","PORNHEAT","PORNHUB","PORNHUBADS","PORNID","PORNINAMINUTE","PORNINFIFTEENSECONDS","PORNISCHEATING","PORNMEMES","PORNSTARHQ","PORNSTARLETHQ","PORNSTARS","PORNVIDS","PORN_GIFS","POSTORGASM","POV","PREGGOPORN","PREMATURECUMSHOTS","PREMIUMSNAPCHAT","PRETTYLITTLECUMSLUTS","PRINCESSPAWG","PROGRESSIVEGROWTH","PRONEBONE","PROSTATEPLAY","PUBLIC","PUBLICBOYS","PUBLICFLASHING","PUBLICNUDITY","PUBLICSEXPORN","PUFFIES","PULSATINGCUMSHOTS","PUSSY","PUSSYJOBS","PUSSYMOUND","PUSSYRATING","PUSSYWEDGIE","QUIVER","RACEPLAY","RACHELSTARR","RAELILBLACK","RANDOMACTSOFBLOWJOB","RANDOMACTSOFMUFFDIVE","RANDOMSEXINESS","RANDOM_ACTS_OF_SEX","RAPEFANTASY","RAPEKINK","RAPE_ROLEPLAY","RATEMYASS","RATEMYBOOBS","RATEMYCOCK","RATEMYNUDEBODY","RATEMYPUSSY","REALAHEGAO","REALGIRLS","REALHOMEPORN","REALITYDICK","REALLIFEHENTAI","REALMOMS","REALPUBLICNUDITY","REALTELARILOVE","REARPUSSY","REDDITORCUM","REDDITSMUSEUMOFFILTH","REDHEADGIFS","REDHEADS","RELUCTANCE","REMYLACROIX","REPRESSEDGONEWILD","RETROUSSETITS","REVERSECOWGIRL","RIDINGXXX","RILEYREID","RIMJOB","RISKYPORN","ROLEPLAYKIK","ROUGHANAL","ROUGHFUCKING","RUBYMAY","RUINEDORGASMS","RULE34","RULE34LOL","RULE34OVERWATCH","RULE34RAINBOWSIX","RULE34_COMICS","RWBYNSFW","SABRINA_NICHOLE","SAGGY","SAMESPECIES","SARAH_XXX","SARAJUNDERWOOD","SASHAGREY","SAUCEFORNSFWADS","SAUCEFORSCIENCE","SCHOOLGIRLSKIRTS","SCISSORING","SCRUBSGONEWILD","SEATTLEGONEWILD","SEETHRU","SEXIESTVIDEOS","SEXINFRONTOFOTHERS","SEXSELLS","SEXTING","SEXTINGFRIENDFINDER","SEXTOYS","SEXTROPHIES","SEXTSTORIES","SEXY","SEXYBUTNOTPORN","SEXYDESIBABES","SEXYFLOWERWATER","SEXYFREX","SEXYGIRLS","SEXYSTORIES","SEXYTUMMIES","SEX_COMICS","SGGONEWILD","SHADMAN","SHAIDENROGUE","SHECAME","SHEFUCKSHIM","SHELIKESITROUGH","SHEMALES","SHEMALESPARADISE","SHEMALE_BIG_COCK","SHESGONNACUM","SHIBBYSAYS","SHINYPORN","SHORTHAIRCHICKS","SHOWERGIRLS","SHOWERSEX","SIMPS","SISSIES","SISSIESINACTION","SISSYCAPTIONS","SISSYCHASTITY","SISSYHYPNO","SISSYKIK","SISSYPERFECTION","SISSYPERSONALS","SISSY_HUMILIATION","SISTERSNSFW","SIZECOMPARISON","SKINNYTAIL","SLEEPPORN","SLIGHTCELLULITE","SLIMANDSTACKED","SLIMTHICK","SLOPPYBLOWJOB","SLUT","SLUTSOFSNAPCHAT","SLUTTYCONFESSIONS","SLUTTYHALLOWEEN","SLUTWIFE","SMALLBOOBS","SMALLTITSBIGASS","SNAPCHATGW","SNAPCHATSEXT","SNAPCHAT_NUDES","SNAPCHAT_SLUTS","SNAPLEAKS","SNEAKYPORN","SNOWWHITES","SOCALGONEWILD","SOCIALMEDIASLUTS","SOFTIES","SOMMERRAY","SONMOM","SOPHIEDEE","SOUNDING","SOURCEPORNMAKER","SOURCES4PORN","SPAGHETTIHENTAI","SPANKING","SPH","SPITROASTED","SPLITVIEW","SPREADEAGLE","SPREADEM","SPREADING","SQUATFUCK","SQUIRTING","SQUIRTING_GIFS","SSBBW","STACKED","STANDINGOUT","STARWARSNSFW","STAWG","STEVENUNIVERSENSFW","STOCKINGS","STPEACH","STRAIGHTGIRLSPLAYING","STRAPONLESBIANS","STREAMERSGONEWILD","STRIPGIRLS","STRIPPERSONTHEJOB","STRUGGLEFUCKING","STRUGGLEPORN","STUFFERS","STUPIDSLUTSCLUB","SUCKINGITDRY","SUCTIONBLOWJOBS","SUCTIONDILDOS","SUICIDEGIRLS","SUMMERTIMESAGA","SUPERHEROPORN","SWENSFW","SWINGERSGW","SWINGERSR4R","TALKEDINTOIT","TANLINES","TEACHERSGONEWILD","TEENHDPORN","TEENSPORNVIDEOS","TEENTITANSPORN","TENTAI","TESSAFOWLER","TGIFS","TGIRLS","THEHIDDENBOOTY","THELOSTWOODS","THERATIO","THE_BEST_NSFW_GIFS","THICCERTHANYOUTHOUGHT","THICK","THICKASIANS","THICKCHIXXX","THICKDICK","THICKER","THICKLOADS","THICKTHIGHS","THICKWHITEGIRLS","THICK_HENTAI","THIGHDEOLOGY","THIGHHIGHS","THINKTANKSEXY","THONGS","THOTCLUB","THREESOME","THROATBARRIER","THROATFUCKING","THROATPIES","THROBBINGCIM","TIGHTDRESSES","TIGHT_SHORTS","TIKTOKNSFW","TINDERNSFW","TINYDICK","TINYTITS","TIPOFMYPENIS","TITFUCK","TITS","TITSONASTICK","TITSTOUCHINGTITS","TITTIES","TITTYDROP","TOOBIG","TOOCUTEFORPORN","TOON_PORN_COMICS","TOPSANDBOTTOMS","TORI_BLACK","TORPEDOTITS","TOTALLYFUCKABLE","TOTALLYSTRAIGHT","TOWELGIRLS","TRAANSFW","TRANSFORMATION","TRANSPORN","TRANS_CAMS","TRAPHENTAI","TRAPS","TRAPSARENTGAY","TRASHYBONERS","TRASHYPORN","TREESGONEWILD","TRIBUTEME","TRUEBIGDICKSTORIES","TRUEFMK","TRUESPH","TRYPOPHOBIA","TSCUM","TSCUMSLUTS","TSONFM","TWERK","TWERKING","TWINGIRLS","TWINKS","TWITCHGONEWILD","UNASHAMED","UNCOMMONPOSES","UNDERWEARGW","UNEXPECTEDSEX","UNEXPECTEDTITTY","UPSKIRT","UPVOTEDBECAUSEBUTT","USEDPANTIES","VAGINA","VALERYALTAMARFANS","VERIFIEDAMATEURS","VERTICALGIFS","VICTORIAMATOSA","VIKING_BARBIE","VIOLETSUMMERSFANS","VIRGINITYEXCHANGE","VOLLEYBALLGIRLS","VOLUPTUOUS","VORE","VOYEURFLASH","VSCOSLUTS","WATCHITFORTHEPLOT","WATERSPORTS","WEDDINGRINGSSHOWING","WEDDINGSGONEWILD","WESTERNHENTAI","WET","WETANDMESSY","WETSPOT","WGBEFOREAFTER","WHALETAIL","WHENITGOESIN","WHIPTRAX","WHITEANDTHICK","WHITECHEEKS","WHOLESOMEHENTAI","WHOOPSGOESTHECONDOM","WHOOTIES","WHOREGASM","WHYEVENWEARANYTHING","WIFE","WIFE2SHARE","WIFEPICTRADING","WIFESHARE","WIFESHARING","WINCEST","WINCESTTEXTS","WITCHER_NSFW","WOAHVICKY","WOMENBENDINGOVER","WOMENINTROUBLE","WOMENOFCOLOR","WOMENOFCOLORXXX","WORKGONEWILD","WORKIT","WORKOUTGONEWILD","WOULDYOUBONEMYMOM","WOULDYOUFUCKMYWIFE","WOWTHISSUBEXISTSNSFW","WRESTLEFAP","WTSSTADAMIT","XCHANGEPILL","XEV_BELLRINGER","XSMALLGIRLS","XSOME","XVR","XXXCAPTIONS","YAOI","YAYAMATEURS","YIFF","YIFFCOMICS","YIFFGIF","YOGAPANTS","YOUBOOBERS","YOUNGPORN","YOUTUBERSGONEWILD","YOUTUBETITTIES","YURI","ZZVIOLETZZ"]

    return (
      <div>
        <div id="nsfwLinks">
          {nsfwLinks.map((value, index)=>{
           return <p key={index} onClick={this.handleChange} name={value}>{value}</p>
          })}
        </div>
        <div className="row">
          <form
            className="col s12 m6 push-m3"
            onSubmit={this.handleSubmit}
            autocomplete="off"
          >
            <div className="row">
              <div className="input-field col s12">
                <input
                  id="reddit"
                  type="text"
                  value={this.state.subreddit}
                  className="validate white red-text"
                  onChange={this.handleChange}
                />
                <label for="reddit">Enter SubReddit:</label>
                <button
                  className="btn waves-effect waves-light col s12"
                  onClick={this.handleNext}
                >
                  Next
                </button>
              </div>
            </div>
          </form>
        </div>
        <div className="media-container">
          <ListImages images={images} />
          <ListVideos video={this.state.data} />
          <ListOtherVids otherVideos={links} />
          <HostedVideos hostVideos={hosted} />
        </div>
      </div>
    );
  }
}

export default App;

/*
  "link fallback url done"
  "rich:video done"
  "hosted:video"
*/
